### ISSUE TITLE
Minimal Layout Error on dub

### ISSUE THREAD

**Issue by EmTee70** [WebFreak001/WebConfig#1]
https://code.dlang.org/packages/web-config

Some html is displayed as source:
 
Below the title:
web-config

```<a href="https://code.dlang.org/packages/web-config" title="Go to web-config"><img src="https://img.shields.io/dub/v/web-config.svg" alt="Dub version"></a> <a href="https://code.dlang.org/packages/web-config" title="Go to web-config"><img src="https://img.shields.io/dub/dt/web-config.svg" alt="Dub downloads"></a> ```

One additional question,  is there an working example on line?

**Comment by WebFreak001** [comment]
it's fixed already but I would need to bump a new release, which I don't want to do just for a readme change
